config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get, :post]

  resources :user_books

  resources :users do
    resources :user_books
  end


  get '/:anything', to: 'application#wrong_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :user_books
    has_many :users, through: :user_books
    
    validates :title, presence: true

    validates :author, presence: true
    scope :rare, -> { where(rare: true)}   
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_books
    has_many :books, through: :user_books

    validates :username, presence: true
    validates :email, presence: true, uniqueness: true
    
    has_secure_password

   
end

app/models/user_book.rb
class UserBook < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates :book_id, :user_id, presence: true

    def self.search(q)
        UserBook.all.select do |book|
            book.book.author.include?(q)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def wrong_page
        render "/wrong_page"
    end

    helper_method :logged_in?, :current_user, :authorized, :set_user_id


    def current_user
        @user = User.find_by_id(session[:user_id])
    end

    def authorized?
        logged_in? && @user == current_user
    end

    def logged_in?
        !current_user.nil?
    end 
    def set_user_id
        if @user
            @user_id= @user.id
        end
    end
end

app/controllers/books_conteroller.rb
class BooksController < ActionController

    def index
        @books = Book.all
    end
end

app/controllers/books_controller.rb
class BooksController < ActionController

    def index
        @books = Book.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        if current_user
            redirect_to user_path(current_user)
        else
        @user = User.new
        end
    end
    def create
        if User.find_by(email: params[:email])
            @user = User.find_by(email: params[:email])
            if  @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                redirect_to '/login', notice: "Email/Password not found"
            end 
        else
            redirect_to '/login', notice: "Email/Password not found"
        end

    end

    def index
        current_user = User.find_by_id(session[:current_user_id])
    end

    def login
    end

    def destroy
        session.clear
        redirect_to login_path
    end

    def google
        @user = User.find_or_create_by(email: auth["info"]["email"], username: auth["info"]["name"]) do |user|
            user.password = SecureRandom.hex(13)
        end
        if @user && @user.id
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
   
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    def index
        current_user
        if params[:user_id]
            friend = User.find_by_id(params[:user_id])
            @user_books = friend.user_books
        else
            @user_books = UserBook.all
        end

        if params[:q]
            @user_books = @user_books.search(params[:q])
        end
    end

    def show
        current_user
        set_user_id
    end
    
    def new
        if logged_in?
            if params[:format]
                @user_book = UserBook.find_by_id(params[:format])
                @user_book.condition = nil
                flash.notice = "Please enter the condition of your book!"
            else
                @user_book = UserBook.new()
                @user_book.book = Book.new()
            end
        else
            redirect_to login_path
        end
    end

    def create
        @user_book = UserBook.new()
        @user_book.book = Book.new()
        if Book.new(author: params[:user_book][:book][:author],
            title: params[:user_book][:book][:title]).valid?
            if logged_in?
                    current_user
                    if book = Book.find_by(author: params[:user_book][:book][:author],
                        title: params[:user_book][:book][:title],
                        genre: params[:user_book][:book][:genre],
                        year: params[:user_book][:book][:year],
                        publisher: params[:user_book][:book][:publisher])
                        @user_book = UserBook.new(condition: params[:user_book][:condition])
                        @user_book.user= current_user
                    else
                        book = Book.new(author: params[:user_book][:book][:author],
                        title: params[:user_book][:book][:title],
                        genre: params[:user_book][:book][:genre],
                        year: params[:user_book][:book][:year],
                        publisher: params[:user_book][:book][:publisher],
                        rare: params[:user_book][:book][:rare])
                        @user_book = UserBook.new(condition: params[:user_book][:condition])
                        @user_book.user= current_user
                    end
                    if book.save 
                        @user_book.book = book
                        if @user_book.save
                            redirect_to user_user_books_path(@user, @userbook)
                            else
                                render :new
                        end
                    else
                        render :new
                    end
            else
                redirect_to login_path     
            end
        else
            @user_book.errors.add(:author_and_title, "must be valid") 
            render :new
        end
    end

    def edit
    end

    def update
        if logged_in? && authorized?
            current_user
            @user_book.condition = params[:user_book][:condition]
            @user_book.book.title = params[:user_book][:book][:title]
            @user_book.book.author = params[:user_book][:book][:author]
            @user_book.book.genre = params[:user_book][:book][:genre]
            @user_book.book.year = params[:user_book][:book][:year]
            @user_book.book.publisher = params[:user_book][:book][:publisher]
            @user_book.book.rare = params[:user_book][:book][:rare]
            if  @user_book.save
                redirect_to user_user_books_path(@user, @userbook)
            else
                redirect_to edit_user_user_book_path(@user, @user_book)
            end
        end
    end

    def destroy
        if logged_in? && authorized?
            @user_book.destroy
            redirect_to user_user_books_path(@user)
        else
            redirect_to login_path
        end
    end

    private
        def user_book_params
            params.require(:user_book).permit(:title, :author, :genre, :year, :publisher, :rare, :condition)
        end
        def set_book
            @user_book = UserBook.find_by_id(params[:id])
        end       
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, :set_user_id, only: [:show, :edit, :update, :destroy, :index]
    
    def index
        current_user
        @users = User.all
    end
    
    def show
        @rare_books = Book.rare

        if logged_in?
        else
            redirect_to login_path
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to @user
        else
            render :edit
        end
    end

    private

    def find_user
        @user = User.find_by_id(params[:id])
    end
    def user_params
        params.require(:user).permit(:password, :email, :username)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
    <h4>Here is all the book!</h4>
    <ul>
    <% @books.each do |book|%>
        <li> <%= link_to book.title, book%> by <%= book.author %><br>
            <%= link_to "clink here to add this book to your library", %>
        <br>
        </li>
    <% end %>
    <h4>To add a new book, <%= link_to "go here", new_user_user_book_path(@user, @user_book) %></h4>
    <h4> Back to <%=link_to "list of owned books", user_books_path %> </h4>
    <h4> Look at <%=link_to "your books", user_user_books_path(@user, @user_books) %> </h4>

app/views/books/new.html.erb
<h2>Save a new book!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shades</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background">
      <div class="container">
        <div class="row">
          <div class="banner">
            <h1> <a href="/">Shades</a></h1>
            <h6> Books are made to be read </h6>
          </div>
        </div>
        <div class="row">
          <div class="well">
            <%= yield %>
          </div>
        
          <footer class="branding"> 
          <% if logged_in? %>    
              <h4>Logged in as <%= current_user.username %> </h4>
              <h4><%= link_to "Log Out", logout_path%> </h4>
              <%else%>
              <h4><%= link_to "Log In", login_path%>
              <h4><%= link_to "Sign Up", signup_path%> </h4>
          <% end %>
              
             
            <small>&copy; 2021 <strong>Shades</strong></small>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/user_books/_form.html.erb
<%= form_with model: @user_book do |f| %>
    <p><%= f.fields_for :book do |ff|%>
        <%= ff.label "Book title"%>
        <%= ff.text_field :title, required:true, value: @user_book.book.title, class: @user_book.errors.any? ? "error-field" : nil  %>
        <br>
        <%= ff.label "Author"%>
        <%= ff.text_field :author, required:true, value: @user_book.book.author, class: @user_book.errors.any? ? "error-field" : nil  %>
        <br>
        <%= ff.label "Genre"%>
        <%= ff.text_field :genre, value: @user_book.book.genre%>
        <br>
        <%= ff.label "Publisher"%>
        <%= ff.text_field :publisher, value: @user_book.book.publisher%>
        <br>    
        <%= ff.label "Year Published"%>
        <%= ff.text_field :year, value: @user_book.book.year%>
        <br>
        Is this a rare book?<%= ff.radio_button :rare, true %> Y <%= ff.radio_button :heat, false %> N
    </p>
    <% end %>

    <% flash.each do |type, msg| %>
      <div class="notice-info">
        <%= msg %> <br>
      </div>
    <% end %>

    <p>
        <%= f.label "Condition" %>
        <%= f.text_field :condition %>
        <br>
        <%= f.submit %>
    </p>
<% end %>

app/views/user_books/_nav.html.erb
<% @user = current_user%>
<h4>To add a new book to your collection, <%= link_to "go here", new_user_user_book_path(@user, @user_book) %> </h4>
<h4> To see all the books in our system, <%=link_to "go here", user_books_path %> </h4>
<h4>To view a list of your books, <%= link_to "go here", user_user_books_path(@user, @user_book) %> </h4>
<h4>To view a list of users, <%= link_to "go here", users_path%> </h4>
<h4>To change your account settings, <%= link_to "go here", edit_user_path(@user)%> </h4>

app/views/user_books/edit.html.erb
<h3>Editing <%=@user_book.book.title %></h3>


<%= render 'form' %>

<%= link_to "Delete this book from your library",  @user_book,  method: :delete, data: { confirm: 'Are you sure?' }%>
<%= render 'nav' %>

app/views/user_books/index.html.erb
<%= form_tag("/user_books", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

    <h4>Here is that library:</h4>
    <ul>
    <% @user_books.each do |book|%>
        <li> <%= link_to book.book.title, book%> by <%= book.book.author %><br>
        Condition: <%= book.condition %>, Owner: <%=book.user.username%><br>
        <br>
        </li>
    <% end %>
<%= render 'nav' %>

app/views/user_books/new.html.erb
<h2>Save a new book!</h2>

<% if @user_book.errors.any? %>
    <% @user_book.errors.full_messages.each do |error| %>
        <h4 class= "error"><%= error %></h4>
    <% end %>
<% end %>

<%= render 'form' %>
<%= render 'nav' %>

app/views/user_books/show.html.erb
<h3>Here's the details of that book.
</h3>
<h4> Owner: <%= @user_book.user.username %></h4>
<h4> Title: <%= @user_book.book.title %></h4>
<h4> Author: <%= @user_book.book.author %></h4>
<h4> Genre: <%= @user_book.book.genre%></h4>
<h4> Publisher: <%= @user_book.book.publisher%></h4>
<h4> Year published: <%= @user_book.book.year%></h4>
<h4> Condition: <%= @user_book.condition %></h4>
<% if @user_book.book.rare == true %>
<h4> 🎉🎉THIS IS A RARE BOOK!🎉🎉</h4>
<%end%>
<br><br><br>
<% if current_user == @user_book.user %>
    <h5>Edit this book <%= link_to "here",  edit_user_user_book_path(@user, @user_book) %></h5>
    <% else %>
    <h5>Add a copy of this book to your collection new <%= link_to "here",  new_user_user_book_path(@user, @user_book) %> </h5>
<% end %>
<%= render 'nav'%>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
    <%= f.label :username%>
    <%= f.text_field :username, required:true, class: @user.errors.any? ? "error-field" : nil  %>
    <br>
    <%= f.label :email%>
    <%= f.email_field :email, required:true, class: @user.errors.any? ? "error-field" : nil  %>
    <br>
    <%= f.label :password%>
    <%= f.password_field :password, required:true, class: @user.errors.any? ? "error-field" : nil  %>
    <%= f.submit %>
<%end%>

app/views/users/edit.html.erb
<br><br><br><br><br><br>

 <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |error| %>
        
            <h4><%= error %></h4>

        <% end %>
    <% end %>
    
<%= render 'form' %>

app/views/users/index.html.erb
<h2>Here's a lit of users. Click on them to check out what books they have!
</h2>
<ul>
<% @users.each do |user|%>
    <li><%= link_to user.username, "/users/#{user.id}/user_books" %></li>
<% end %>
</ul>
<%= link_to "home", "/"%>

app/views/users/new.html.erb
<br><br><br><br><br><br>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
        <h4 class= "error"><%= error %></h4>
    <% end %>
<% end %>

<%= render 'form' %>

<br><br>
<h4>Already have an account? <%=link_to "Login here!", login_path %> </h4>

app/views/users/show.html.erb
<h4> Hey <%=@user.username%>!! Welcome back!
</h4>
<h3>Here's a list of our rare books!</h3>
<ul>
<% @rare_books.each do |book|%>
   <h5> <%= book.title%><br></h5>
<%end%>
</ul>
<%= render 'user_books/nav' %>